# Generated by Django 2.0.7 on 2018-08-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feel', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('hnumber', models.CharField(max_length=64)),
            ],
        ),
    ]
